### ISSUE TITLE
re-add organization members removed due lack of 2FA

### ISSUE THREAD

**Issue by ssbarnea** [pycontribs/meta#1]
Once you reactivate 2FA on your account please add a comment here in order to re-invite you to the organization.

On 2019-10-28, I was forced to remove all accounts that did not have 2FA as part of security hardening process.

**Comment by shortmann** [comment]
please add me again, I have now 2FA enabled.

**Comment by ssbarnea** [comment]
Done for @shortmann and @sshnaidm and looking for others.

**Comment by decentral1se** [comment]
Can I be re-added as well? Got locked out of my account (:man_facepalming:) but now am back in the driving seat. 2FA is re-enabled.
